/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#1b1c1c",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "tertiary-fixed": "#a7edff",
        secondary: "#77574d",
        "on-tertiary-container": "#004854",
        "on-surface-variant": "#544438",
        "on-primary-container": "#693300",
        "on-secondary-fixed": "#2c160e",
        "on-secondary-container": "#795950",
        "surface-container-low": "#f6f3f2",
        "surface-container-highest": "#e4e2e1",
        "surface-bright": "#fcf9f8",
        "on-surface": "#1b1c1c",
        "inverse-primary": "#ffb783",
        "on-primary-fixed": "#301400",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        surface: "#fcf9f8",
        primary: "#944a00",
        "on-primary-fixed-variant": "#713700",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dcd9d9",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#5d4037",
        "secondary-fixed": "#ffdbd0",
        "on-tertiary-fixed-variant": "#004e5b",
        "tertiary-fixed-dim": "#57d6f1",
        "tertiary-container": "#34bdd7",
        "on-primary": "#ffffff",
        "surface-variant": "#e4e2e1",
        "secondary-fixed-dim": "#e7bdb1",
        "secondary-container": "#fed3c7",
        "primary-container": "#ff9238",
        tertiary: "#006878",
        outline: "#867366",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0f0",
        "primary-fixed-dim": "#ffb783",
        background: "#fcf9f8",
        "surface-tint": "#944a00",
        "primary-fixed": "#ffdcc5",
        "outline-variant": "#d9c2b3",
        "on-tertiary-fixed": "#001f25",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
      },
      fontFamily: {
        headline: ["Be Vietnam Pro", "Noto Sans KR", "sans-serif"],
        body: ["Be Vietnam Pro", "Noto Sans KR", "sans-serif"],
        label: ["Be Vietnam Pro", "Noto Sans KR", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
